AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Change sets - S3 bucket (uksb-1q9p31idr) (tag:changesets).

Parameters:
  BucketName:
    Description: Name of the Amazon S3 bucket you wish to create
    Type: String
    AllowedPattern: ^(?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
    ConstraintDescription: Bucket name can include numbers, lowercase letters, uppercase letters, periods (.), and hyphens (-). It cannot start or end with a hyphen (-).

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
