AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Workshop - Cloud9 IDE (uksb-1q9p31idr).

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W2506

Parameters:
  InstanceType:
    Description: The type of instance to connect to the environment (for example, t2.micro).
    Type: String
    Default: t2.micro
    AllowedPattern: ^[a-z][1-9][.][a-z0-9]+$

  ImageId:
    Description: The AMI alias for the Amazon Machine Image (AMI) that's used to create the EC2 instance.
    Type: String
    AllowedValues:
      - amazonlinux-1-x86_64
      - amazonlinux-2-x86_64
      - ubuntu-18.04-x86_64
    Default: amazonlinux-2-x86_64

  AutoHibernationTimeoutMinutes:
    Description: The number of minutes until the running instance is shut down after the environment was last used.
    Type: Number
    Default: 30
    MinValue: 0
    MaxValue: 20160

  ConnectionType:
    Description: The connection type used for connecting to an Amazon EC2 environment. Valid values are CONNECT_SSM (default) and CONNECT_SSH.
    Type: String
    AllowedValues:
      - CONNECT_SSM
      - CONNECT_SSH
    Default: CONNECT_SSM

  ProjectName:
    Description: The name of the environment.
    Type: String
    Default: AWS CloudFormation Workshop

Resources:
  AWSCloud9SSMAccessRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: This is service role which requires explicit naming.
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloud9.amazonaws.com
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Service linked role for AWS Cloud9
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloud9SSMInstanceProfile
      RoleName: AWSCloud9SSMAccessRole

  AWSCloud9SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: AWSCloud9SSMInstanceProfile
      Path: /cloud9/
      Roles:
        - !Ref AWSCloud9SSMAccessRole

  AWSCloudFormationWorkshopEnv:
    Type: AWS::Cloud9::EnvironmentEC2
    DependsOn:
      - AWSCloud9SSMInstanceProfile
    Properties:
      AutomaticStopTimeMinutes: !Ref AutoHibernationTimeoutMinutes
      ConnectionType: !Ref ConnectionType
      Description: AWS CloudFormation workshop - Cloud9 IDE
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      Repositories:
        - RepositoryUrl: https://github.com/aws-samples/cfn101-workshop.git
          PathComponent: cfn101-workshop
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  Cloud9URL:
    Description: Cloud9 Environment
    Value: !Join
      - ""
      - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/home/environments/
        - !Ref AWSCloudFormationWorkshopEnv
