AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Template and stack (uksb-1q9p31idr).

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
