AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Linting and testing - SQS queue template (uksb-1q9p31idr) (tag:linting-and-testing).

Resources:
  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      # Use `cfn-lint` to find issues on this example template, and
      # then fix issues you found
      DelaySeconds: 1000
      Tag:
        - Key: Name
          Value: workshop-sqs-queue
        - Key: ProjectName
          Value: Example

Outputs:
  SqsQueueURL:
    Description: The URL of your Amazon SQS Queue
    Value: !Ref SqsQueue

  SqsQueueName:
    Description: The name of your Amazon SQS Queue
    Value: !GetAtt SqsQueue.Name
