AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - policy-as-code with Guard - example S3 bucket (uksb-1q9p31idr) (tag:policy-as-code).

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
