AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation workshop - Dynamic references - Lambda memory size (uksb-1q9p31idr) (tag:dynamic-references).
Resources:
  FunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Path: /
  ## Lambda Resource Goes Here
