AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Stack policy and prevention controls - deletion policy (uksb-1q9p31idr) (tag:stack-policy).

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W3011

Resources:
  SNSTopic:
    DeletionPolicy: Retain
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Topic-2
