AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Update behaviors of stack resources (uksb-1q9p31idr).

Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    AllowedValues: [t2.micro, t2.small, t2.medium]
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      Monitoring: true
      Tags:
        - Key: Name
          Value: cfn-workshop-new-value
