AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: test-bucket-compliant
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
