AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Troubleshooting provisioning errors - SQS Queue (uksb-1q9p31idr)

Parameters:
  QueueNamePrefix:
    Type: String
    Default: my-example-queue

Resources:
  ExampleDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: !Sub '${QueueNamePrefix}-dead-letter.fifo'

  ExampleSourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ExampleDeadLetterQueue.Arn
        maxReceiveCount: 5
      QueueName: !Sub '${QueueNamePrefix}-source.fifo'

  ExampleDeadLetterQueueParameter:
    Type: AWS::SSM::Parameter
    Properties:
      AllowedPattern: ^arn:aws([-a-z0-9-]*[a-z0-9])*:sqs:[a-z0-9-]+:[0-9]{12}:[a-zA-Z0-9_-]{1,80}(\.fifo){0,1}$
      Description: Parameter for the ExampleDeadLetterQueue ARN value
      Name: workshop-example-dead-letter-queue
      Type: String
      Value: !GetAtt ExampleDeadLetterQueue.Arn

  ExampleSourceQueueParameter:
    Type: AWS::SSM::Parameter
    Properties:
      AllowedPattern: ^arn:aws([-a-z0-9-]*[a-z0-9])*:sqs:[a-z0-9-]+:[0-9]{12}:[a-zA-Z0-9_-]{1,80}(\.fifo){0,1}$
      Description: Parameter for the ExampleSourceQueue ARN value
      Name: workshop-example-source-queue
      Type: String
      Value: !GetAtt ExampleSourceQueue.Arn
