AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop lab for looping over collections (uksb-1q9p31idr) (tag:looping-over-collections).

Transform: AWS::LanguageExtensions

Resources:
  Fn::ForEach::S3Buckets:
    - S3BucketLogicalId
    - [S3Bucket1, S3Bucket2, S3Bucket3]
    - ${S3BucketLogicalId}:
        Type: AWS::S3::Bucket
        Properties:
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: aws:kms
          LifecycleConfiguration:
            Rules:
              - Id: Example Glacier Rule
                ExpirationInDays: 365
                Status: Enabled
                Transitions:
                  - TransitionInDays: 30
                    StorageClass: GLACIER
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          Tags:
            - Key: Name
              Value: aws-cloudformation-workshop
