AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions

Description: AWS CloudFormation workshop - Language extensions (uksb-1q9p31idr).

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket
