version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - hugo version
        - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "browser_download_url.*hugo_extended.*_Linux-64bit\.tar\.gz" | cut -d '"' -f 4 | wget -qi -
        - tarball=$(find . -name "*Linux-64bit.tar.gz")
        - tar -xzf $tarball hugo
        - mv hugo /usr/bin/hugo
        - rm -rf $tarball
        - hugo version
    build:
      commands:
        - cd workshop
        - hugo
  artifacts:
    baseDirectory: workshop/public
    files:
      - '**/*'
  cache:
    paths: []
