AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - drift detection challenge (uksb-1q9p31idr) (tag:drift-detection).

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W3011

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  Instance1:
    DeletionPolicy: Retain
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      UserData: !Base64 |
        #!/usr/bin/env bash
        echo Hello Universe

  Bucket1:
    Type: AWS::S3::Bucket
